module Stimulus::Manifest
  extend self

  def generate_from(controllers_path)
    manifest = extract_controllers_from(controllers_path).collect do |controller_path|
      import_and_register_controller(controllers_path, controller_path)
    end

    manifest.uniq
  end

  def write_index_from(controllers_path, manifest_type = :imports)
    File.open(Rails.root.join(controllers_path.join("index.js")), "w+") do |index|
      task = manifest_type == :config_hash ? "stimulus:lazy_manifest:update" : "stimulus:manifest:update"
      index.puts "// This file is auto-generated by ./bin/rails #{task}"
      if manifest_type == :imports
        index.puts "// Run that command whenever you add a new controller or create them with"
        index.puts "// ./bin/rails generate stimulus controllerName"
      else
        index.puts "// Run that command whenever you add a new controller"
      end
      index.puts
      index.puts %(import { application } from "./application")

      if manifest_type == :config_hash
        index.puts generate_lazy_load_from_config_from(controllers_path)
      else
        index.puts generate_from(controllers_path)
      end
    end
  end

  def generate_lazy_load_from_config_from(controllers_path)
    controller_paths = extract_controllers_from(controllers_path)
    hash_lines = controller_paths.map do |controller_path|
      relative_controller_path = controller_path.relative_path_from(controllers_path)
      module_path = module_path_from(relative_controller_path)
      tag_name = tag_name_from(module_path)

      %(  "#{tag_name}": () => import("./#{module_path}"),)
    end

    <<-JS

import { lazyLoadControllersFromConfig } from "@hotwired/stimulus-loading"
lazyLoadControllersFromConfig({
#{hash_lines.join("\n")}
}, application)
    JS
  end

  def import_and_register_controller(controllers_path, controller_path)
    relative_controller_path = controller_path.relative_path_from(controllers_path)
    module_path = module_path_from(relative_controller_path)
    controller_class_name = controller_class_name_from(module_path)
    tag_name = tag_name_from(module_path)

    <<-JS

import #{controller_class_name} from "./#{module_path}"
application.register("#{tag_name}", #{controller_class_name})
    JS
  end

  def module_path_from(relative_controller_path)
    relative_controller_path.to_s.split('.').first
  end

  def tag_name_from(module_path)
    module_path.remove(/_controller/).gsub(/_/, "-").gsub(/\//, "--")
  end

  def controller_class_name_from(module_path)
    module_path.underscore.camelize.gsub(/::/, "__")
  end

  def extract_controllers_from(directory)
    (directory.children.select { |e| e.to_s =~ /_controller(\.\w+)+$/ } +
      directory.children.select(&:directory?).collect { |d| extract_controllers_from(d) }
    ).flatten.sort
  end
end
